version: 2

jobs:
  build:
    machine: true
    environment:
      CHANGE_MINIKUBE_NONE_USER: true
      MINIKUBE_DRIVER: "none"
      REACTIONCOMMERCE_NAME: "circleci-build-test"
      MONGO_RELEASE_NAME: "circleci-mongodb-test"
      REACTION_API_NAME: "grape-ape-api"
      REACTIONCOMMERCE_REPO: "reactioncommerce/reaction"
      REACTIONCOMMERCE_TAG: "latest"
      REPLICAS: 2
      MONGO_REPLICAS: 3
      MINIKUBE_MEMORY: 7777
      MINIKUBE_CPU: 4
      HOME: /opt/circleci
    steps:
      - restore_cache:
          keys:
            - r8s-v3-{{ arch }}-{{ .Branch }}-{{ .Revision }}
            - r8s-v3-{{ arch }}-{{ .Branch }}
            - r8s-v3

      - checkout

      - run: .circleci/install.sh
      - run: touch $HOME/.bashrc $HOME/.bash_profile $HOME/.zshrc $HOME/.profile
      - run: /usr/bin/time -v make -e run_dotfiles
      - run: bash .ci/envtest.sh
      - run: /usr/bin/time -v make -e linuxreqs
      - run: /bin/bash -l -c "source /opt/circleci/.bashrc && /usr/bin/time -v make -e ci"
      - run: /bin/bash -l -c "source /opt/circleci/.bashrc && /usr/bin/time -v make -e .prom2.rn"
      - run: /bin/bash -l -c "source /opt/circleci/.bashrc && /usr/bin/time -v make -e view-monitoring"

      - save_cache:
          key: r8s-v3-{{ arch }}-{{ .Branch }}-{{ .Revision }}
          paths:
            - /home/circleci/.r8s
            - /home/circleci/.minikube
            - ".git"
