# Default values for mongonetes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
mongoReplicaCount: 3
image:
  repository: mongo
  tag: 3.4
  pullPolicy: IfNotPresent
service:
  name: mongo
  type: ClusterIP
  externalPort: 27017
  internalPort: 27017
ingress:
  enabled: false
  # Used to create an Ingress record.
  hosts:
    - reactioncommerce.local
  annotations:
    kubernetes.io/ingress.class: reactioncommerce
    kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

#mongonetes specific values
mongonetesClusterDomain: cluster.local

##
persistence:
  enabled: false
  ## mongodb data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 8Gi
