apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-reaction-config
data:
  reaction.email: {{ .Values.reactionEmail }}
  reaction.user: {{ .Values.reactionUser }}
  reaction.auth: {{ .Values.reactionAuth }}
  reaction.root_url: {{ .Values.reactionRoot_url }}
  reaction.hostname: {{ .Values.reactionHostname }}
  reaction.mongo_url: {{ template "mongodb_replicaset_url" . }}
