apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "reactioncommerce.fullname" . }}
  labels:
    app: {{ template "reactioncommerce.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "reactioncommerce.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          env:
            - name: ROOT_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-reaction-config
                  key: reaction.root_url
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-reaction-config
                  key: reaction.mongo_url
            - name: REACTION_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-reaction-config
                  key: reaction.user
            - name: REACTION_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-reaction-config
                  key: reaction.email
            - name: REACTION_AUTH
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-reaction-config
                  key: reaction.auth
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: 240
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
