# Default values for reactioncommerce
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: reactioncommerce/reaction
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: reactioncommerce
  type: ClusterIP
  externalPort: 3001
  internalPort: 3000
ingress:
  enabled: false
  # Used to create an Ingress record.
  hosts:
    - reactioncommerce.local
  annotations:
    kubernetes.io/ingress.class: reactioncommerce
    kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

# mongo specificy values
mongodbReleaseName: massive-mongonetes
mongodbName: reactionetesdb
mongodbReplicaSet: rs0
mongodbPort: 27017
mongodbUrl: 'mongodb://{{ .Values.mongodbReleaseName }}-mongodb-replicaset-0:{{ .Values.mongodbPort }},{{ .Values.mongodbReleaseName }}-mongodb-replicaset-1:{{ .Values.mongodbPort }},{{ .Values.mongodbReleaseName }}-mongodb-replicaset-2:{{ .Values.mongodbPort }}/{{ .Values.mongodbName }}?replicaSet={{ .Values.mongodbReplicaSet }} '

# reaction specific values
reactioncommerceClusterDomain: cluster.local
reactionEmail: 'admin@localhost'
reactionUser: 'admin'
reactionAuth: 'r3@cti0n'
# No 'https://' on this it will be added later
reactionHostname:  'reactioncommerce.example.com'
reactionRoot_url:  'http://reactioncommerce.example.com'
